clients:
    stew:
        joystick0:
            - BUTTON_LEFT_BUMPER
            - BUTTON_RIGHT_BUMPER
            - BUTTON_BACK
            - BUTTON_START
            - BUTTON_GUIDE
            - BUTTON_LEFT_THUMB
            - BUTTON_RIGHT_THUMB
            - BUTTON_DPAD_UP
            - BUTTON_DPAD_RIGHT
            - BUTTON_DPAD_DOWN
            - BUTTON_DPAD_LEFT
            - BUTTON_CROSS
            - BUTTON_CIRCLE
            - BUTTON_SQUARE
            - BUTTON_TRIANGLE
            - AXIS_LEFT_X
            - AXIS_LEFT_Y
            - AXIS_RIGHT_X
            - AXIS_RIGHT_Y
            - AXIS_LEFT_TRIGGER
            - AXIS_RIGHT_TRIGGER

#        joystick1:
#            - BUTTON_DPAD_UP
#            - BUTTON_DPAD_RIGHT
#            - BUTTON_DPAD_DOWN
#            - BUTTON_DPAD_LEFT
    alextopher:
        joystick0:
            - BUTTON_DPAD_UP
            - BUTTON_DPAD_RIGHT
            - BUTTON_DPAD_DOWN
            - BUTTON_DPAD_LEFT

mapping:
    BUTTON_CROSS: z             # jump
    BUTTON_CIRCLE: a            # focus
    BUTTON_SQUARE: x            # attack
    BUTTON_TRIANGLE: d          # dream nail
    BUTTON_RIGHT_BUMPER: f      # quick cast
    BUTTON_START: esc           # pause
    BUTTON_BACK: i              # inventory
    BUTTON_LEFT_BUMPER: tab     # map
    BUTTON_DPAD_UP: up          # movement
    BUTTON_DPAD_RIGHT: right    # movement
    BUTTON_DPAD_DOWN: down      # movement
    BUTTON_DPAD_LEFT: left      # movement

    AXIS_LEFT_TRIGGER: s        # super dash
    AXIS_RIGHT_TRIGGER: c       # dash

    AXIS_LEFT_X: left right     # movement
    AXIS_LEFT_Y: up down        # movement
